### ISSUE TITLE
confused

### ISSUE THREAD

**Issue by ghost** [blab/roka#7]
@alliblk The input file in your R script "clockprior_daytoyear.R" is "Francois_strictLog.tsv", could you please send this file to me, thanks. BTW, are you sure the original log file has mut rate in days?

**Comment by alliblk** [comment]
@lixingguang The file referenced in that script was from an original BEAST run from our collaborators, and yes, the clock was calibrated in subs/site/day, which is why I wrote the script to transform it to subs/site/year. I should actually probably remove this script because it's not necessary for any of the analysis we performed, it was just something I wrote to transform a file that a collaborator sent. That said, if it's useful to you, any BEAST log file will work, although you should be sure to change the burn-in parameters as necessary for however many states you sampled and the length of your MCMC chain.
